- changed base distro to Ubuntu 16.10
- added ondrej repository for PHP 7.1

- added GPG key of Frank Denis <github@pureftpd.org>

- added dirmngr package for required template "dirmngr-conf.skel"

- fixed if-statement (Dockerfile is using /bin/sh as interpreter, so no bash conditional expressions allowed)

diff --git a/docker/Dockerfile.airship b/docker/Dockerfile.airship
--- a/docker/Dockerfile.airship
+++ b/docker/Dockerfile.airship
@@ -1,25 +1,28 @@
-FROM ubuntu:16.04
+FROM ubuntu:16.10
 
-RUN apt-get update
+RUN apt-get -y update && apt-get -y install software-properties-common
+# a utf-8 locale is needed to make the import of the ondrej repo work
+RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php && apt-get -y update
 RUN apt-get -y upgrade
 RUN apt-get -y install wget git composer postgresql php7.1 php7.1-cli \
                        php7.1-fpm php7.1-json php7.1-pgsql php7.1-curl \
                        php7.1-xml php7.1-dev php7.1-zip php7.1-mbstring \
                        composer apache2 php-pear libapache2-mod-php7.1 \
-                       php7.1-gd
+                       php7.1-gd dirmngr
 
 RUN rm -f /etc/apache2/sites-enabled/000-default.conf
 RUN a2enmod rewrite
 
+RUN gpg --recv-keys 54A2B8892CC3D6A597B92B6C210627AABA709FE1
 RUN git clone https://github.com/jedisct1/libsodium.git /tmp/sodium
 WORKDIR /tmp/sodium
 RUN git tag -v 1.0.11
-RUN if [[ $? -eq 0 ]]; then \
-        git checkout tags/1.0.11 \
+RUN if [ $? -eq 0 ]]; then \
+        git checkout tags/1.0.11 ; \
     else \
-        echo "Invalid signature for libsodium tag" \
-        exit 1 \
-    endif
+        echo "Invalid signature for libsodium tag" ; \
+        exit 1 ; \
+    fi
 RUN ./autogen.sh
 RUN ./configure && make distcheck
 RUN make install
